### ISSUE TITLE
Token addition only appears on gateway bridge but not on v2 bridge

### ISSUE THREAD

**Issue by okhaimie-dev** [ethereum-optimism/ethereum-optimism.github.io#229]
**Describe the bug**
My recent PR was approved to add BANK token to OP bridge, but the issue is that BANK token only appears on gateway bridge and not the new v2 Optimism bridge.
https://app.optimism.io/bridge/deposit

**To Reproduce**
1. Go to 'https://app.optimism.io/bridge/deposit'
2. Click on 'the ETH dropdown'
3. Scroll down and TOKEN in this case BANK is suppose to appear on bridge

**Expected behavior**
I was expecting TOKEN in this case BANK to appear on v2 bridge after following the guide to add token to bridge.

**Screenshots**

v2 Bridge
![image](https://user-images.githubusercontent.com/57156589/197008618-e52ee7bc-6f24-4e69-af44-f9e1c6280f76.png)

Gateway Bridge
![image](https://user-images.githubusercontent.com/57156589/197009103-af368e9d-6b7c-498e-9490-f52a3262bf23.png)

**Additional context**

**Comment by roninjin10** [comment]
This will show up next time we update the new bridge

**Comment by okhaimie-dev** [comment]
Hi @roninjin10 just checking to know if there is a set date for the next update

**Comment by roninjin10** [comment]
Tuesday afternoon pacific time.   We normally would have already deployed by now as we deploy tuesday through thursday but because of a big breaking change we are shipping we were on a bit of hiatus at the time your pr landed

**Comment by okhaimie-dev** [comment]
Hi @roninjin10 just checking in. I understand you mentioned something about a breaking change so it's okay if y'all haven't gotten to it yet

**Comment by roninjin10** [comment]
Yup apologies.  Because I shipped a bug our release today was broken and we couldn't release it.  Tomorrow we should be good.  I'll update you as soon as we release it so you are first to know

**Comment by roninjin10** [comment]
Hey @okhaimie-dev still trying to get this deployed but running into issues.    We got it ready to deploy at least but can't pull trigger on the deploy til tomorrow.   Will continue to have you update.   Confirming we see your token on staging.

Apologies again about this.  We normally deploy everyday without a hitch.  This is just bad timing that we are rolling out a brand new API now. 
 
<img width="409" alt="image" src="https://user-images.githubusercontent.com/35039927/198154326-2a1e9967-9aa0-49a5-a889-decf96b88d2b.png">

**Comment by roninjin10** [comment]
Will reopen til it's deployed

**Comment by okhaimie-dev** [comment]
Alright thanks, for keeping me in the loop. I appreciate y'all.

**Comment by zainbacchus** [comment]
Hey @okhaimie-dev confirming this is now on app.optimism.io/bridge :)

**Comment by zainbacchus** [comment]
Oops! My mistake did not mean to delete your comment!

**Comment by okhaimie-dev** [comment]
Yay!! Thanks. I appreciate your team. Y'all are awesome

**Comment by okhaimie-dev** [comment]
I am back again, I can't find BANK on the bridge anymore

**Comment by okhaimie-dev** [comment]
@zainbacchus @roninjin10

**Comment by technicallykind** [comment]
When do you expect the next v2 update will push? @roninjin10
