### ISSUE TITLE
Major version bump needed

### ISSUE THREAD

**Issue by just-toby** [ethereum-optimism/ethereum-optimism.github.io#307]
**Describe the request**
At Uniswap we expect a major version bump when tokens are removed from a token list. It seems this list removed tokens recently, so would you be able to bump the major version number?

**To Reproduce**
Note that the token removal caused only a minor version change.

**Expected behavior**
The token removal should cause a major version change.

**Comment by roninjin10** [comment]
Done will keep this in mind in future https://github.com/ethereum-optimism/ethereum-optimism.github.io/commit/b967124539d9df8182e4b15cc897934dea83353e
