### ISSUE TITLE
It doesn't work when selects rETH(StaFi) on the bridge

### ISSUE THREAD

**Issue by Tore19** [ethereum-optimism/ethereum-optimism.github.io#349]
<img width="580" alt="image" src="https://user-images.githubusercontent.com/10955745/231917605-6f419eb4-6384-4448-8dbb-8eebf7e25c58.png">

Hi, when I select rETH(StaFi) here(https://app.optimism.io/bridge/deposit), it doesn't work, seems it selects rETH(Rocket Pool ETH).

**Comment by roninjin10** [comment]
Hey there @Tore19 ,

We reverted your pr until we can further investigate this issue.   Sorry for the inconvenience

**Comment by Tore19** [comment]
@roninjin10 Hi, thanks for your feedback. Really appreciate that if the PR can be merged again ASAP because we plan to open it to users on Optimism next week.

**Comment by zainbacchus** [comment]
Hi @Tore19 ! We'll do our best to get the PR re-merged but need to make some UI changes before this can happen. Thank you for the patience. 

In the interim your community can interact directly with the contract or use the "Custom token" functionality. 

<img width="454" alt="Screenshot 2023-04-14 at 12 08 24 PM" src="https://user-images.githubusercontent.com/54366928/232134801-b1b8aa6f-a672-420e-bb07-0c947de3b31a.png">

**Comment by Tore19** [comment]
Hi @zainbacchus ! Great! We will try this functionality. Thanks!

**Comment by Tore19** [comment]
<img width="734" alt="image" src="https://user-images.githubusercontent.com/10955745/232194159-aeedf1c4-b9d6-4bd2-8887-c7ebaff4d078.png">

Hi @zainbacchus  I added rETH(0x6c2f7b6110a37b3b0fbdd811876be368df02e8b0) using the "Custom token" functionality. But seems the bridge can not load my rETH balance on Ethereum. There should be 0.01979723956984157 rETH on my account(https://etherscan.io/token/0x9559aaa82d9649c7a7b220e7c461d2e74c9a3593?a=0x111f1B41f702c20707686769a4b7f25c56C533B2). 

Please check. Thanks!

**Comment by zainbacchus** [comment]
Thanks for the flag! We'll run down that issue. Good news is we'll likely be able to remerge rETH by tomorrow. Thanks for your patience.

**Comment by zainbacchus** [comment]
Going to close this issue as rETH is accessible via the bridge. LMK if you have any other questions

**Comment by wetezos** [comment]
Hi @zainbacchus Thanks for your feedback. But where I select rETH(StaFi), the bridge still can not show my rETH balance on Ethereum. There should be 0.01979723956984157 rETH on my account(https://etherscan.io/token/0x9559aaa82d9649c7a7b220e7c461d2e74c9a3593?a=0x111f1B41f702c20707686769a4b7f25c56C533B2). Please help to check again. Thanks!

**Comment by Tore19** [comment]
<img width="1300" alt="image" src="https://user-images.githubusercontent.com/10955745/232951281-62991d16-8a4e-4567-8aed-3d5001686997.png">

Hi @zainbacchus Thanks for your feedback. But where I select rETH(StaFi), the bridge still can not show my rETH balance on Ethereum. There should be 0.01979723956984157 rETH on my account(https://etherscan.io/token/0x9559aaa82d9649c7a7b220e7c461d2e74c9a3593?a=0x111f1B41f702c20707686769a4b7f25c56C533B2). Please help to check again. Thanks!

**Comment by Tore19** [comment]
The FIS balance can be shown. But  it was failed when we approved the transaction. Error: "out of gas". Weird. 

https://etherscan.io/tx/0x28d6b3d8602736a3f921e957b4ddaabc6a664a380322266e7ea8ccc536d2c36c

**Comment by tremarkley** [comment]
It looks like you may still have the "Custom token" version of rETH selected. Can you try re-selecting rETH without using the "Custom token" version and then seeing if the balance displays properly?

**Comment by Tore19** [comment]
<img width="1433" alt="image" src="https://user-images.githubusercontent.com/10955745/233234085-ffa63279-1868-49aa-a612-0777efe20b89.png">

Hi @tremarkley I select rETH here(No "Custom" option now), but the balance is still 0.

I checked the local storage. Seems there is "customTokens" field in "BridgeState". I tried delete the "BridgeState". But "customTokens" still exist after I refresh the page. Is the balance issue related to this field?

**Comment by Tore19** [comment]
Great! Thanks!

**Comment by tremarkley** [comment]
@Tore19 can you check again? Just pushed a change that should resolve the issue

**Comment by Tore19** [comment]
Hi @tremarkley We will check later. Thanks!

**Comment by Tore19** [comment]
@tremarkley It works now. Thanks!
