### ISSUE TITLE
CORS Policy to support color extraction in Uniswap App

### ISSUE THREAD

**Issue by willhennessy** [ethereum-optimism/ethereum-optimism.github.io#36]
The Uniswap App is unable to perform color extraction on token logo images hosted at `ethereum-optimism.github.io/logos`  due to the CORS policy.

`Access to image at 'https://ethereum-optimism.github.io/logos/SNX.svg' from origin 'https://app.uniswap.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
`

Can we relax the CORS policy to support this use case?

**To Reproduce**
1. Go to the Add Liquidity page in uniswap app: https://app.uniswap.org/#/add/0x6fd9d7AD17242c41f7131d257212c54A0e816691/0x94b008aA00579c1307B0EF2c499aD98a8ce58e58/3000

**Expected behavior**
The slider handles on the price chart should match the color of the tokens. In the example above, pink for UNI and Green for USDT.
https://github.com/Uniswap/interface/issues/2049

**Screenshots**
<img width="1434" alt="Screen Shot 2021-11-01 at 7 16 21 PM" src="https://user-images.githubusercontent.com/5455577/139754278-1c25de84-6483-44ca-aece-a08f95d2a0d5.png">

**System Specs:**
 - OS: Chrome

**Comment by elenadimitrova** [comment]
I see this is showing correctly atm. Closing but please reopen if still an issue.

![Screenshot 2021-12-29 at 11 56 26](https://user-images.githubusercontent.com/703848/147650035-87a2fb98-a197-49d8-8c8c-622f35db3276.png)
