### ISSUE TITLE
Add PGN network to Superchain Token List

### ISSUE THREAD

**Issue by zainbacchus** [ethereum-optimism/ethereum-optimism.github.io#409]
Maintainers: @kevinrolsen, @Kweiss, @enidavis

{
    "l1ChainId": "11155111",
    "l2ChainId": "58008",
    "l1Addresses": {
        "AddressManager": "0x0Ad91488288BBe60ff38258785568A6D1EB3B983",
        "BondManager": "0x0000000000000000000000000000000000000000",
        "CanonicalTransactionChain": "0x0000000000000000000000000000000000000000",
        "L1CrossDomainMessenger": "0x97f3558Ce48FE71B8CeFA5497708A49531D5A8E1",
        "L1StandardBridge": "0xFaE6abCAF30D23e233AC7faF747F2fC3a5a6Bfa3",
        "L2OutputOracle": "0xD5bAc3152ffC25318F848B3DD5dA6C85171BaEEe",
        "OptimismPortal": "0xF04BdD5353Bb0EFF6CA60CfcC78594278eBfE179",
        "StateCommitmentChain": "0x0000000000000000000000000000000000000000"
    }
}

**Comment by tremarkley** [comment]
Is the L2Standard bridge address for PGN: `0x4200000000000000000000000000000000000010`? Also, is there an RPC provider that can be used for the automated checks we perform? That will need to be added [here](https://github.com/ethereum-optimism/ethereum-optimism.github.io/blob/15be6187a2a7baac473ad7782c6100ab232ba283/src/chains.ts#L6-L41)

**Comment by annieke** [comment]
here's the gitcoin block explorer: https://explorer.publicgoods.network/ (just asked for a block explorer)

**Comment by Kweiss** [comment]
the mainnet details are as follows:

RPC: https://rpc.publicgoods.network
Chain ID: 424
Token: Eth
Decimal: 18
Explorer: https://explorer.publicgoods.network

Full details can be found in our docs here: https://docs.publicgoods.network/network-and-contract-details

cc @annieke

**Comment by Kweiss** [comment]
Here is a PR as well - https://github.com/ethereum-optimism/ethereum-optimism.github.io/pull/433

Would love confirmation I have the new variables configured properly as I had to add Sepolia as well. 🙏

**Comment by annieke** [comment]
cc @hamdiallam who's reviewing this week :)
