### ISSUE TITLE
Where's the UI to bridge Base tokens?

### ISSUE THREAD

**Issue by chicken-juju** [ethereum-optimism/ethereum-optimism.github.io#632]
@roberto-bayardo

As I understand

- The [official base bridge](https://bridge.base.org/withdraw) only supports a small number of tokens. Tokens added to this repo under Base (eg. $ALI, $TETU, $SEAM) have not been whitelisted on [bridge.base.org](https://bridge.base.org). Unlike [Optimism's bridge page](https://app.optimism.io/bridge/withdraw), the base page doesn't support custom addresses.
- Bridge aggregators like [jumper.exchange](https://jumper.exchange/) and [rango.exchange](https://rango.exchange) do not support Base's standard bridge. I tested this by trying to bridge out USDbC, it gets routed via stargate.

Is there a UI page, official or 3rd party to bridge custom ERC20 tokens? How are existing projects doing it? We do not want to build a custom UI.

**Comment by AlexBHarley** [comment]
@chicken-juju we've received a grant from the Optimism Foundation to build a Superchain bridge interface. You can find it here https://superbridge.app, we support Base and all the tokens in this token list.

**Comment by wbnns** [comment]
@chicken-juju 

+1 https://superbridge.app/base that Alex mentioned 👍
