### ISSUE TITLE
Token List 3.2.2 update fails to load on Uniswap due to version

### ISSUE THREAD

**Issue by willhennessy** [ethereum-optimism/ethereum-optimism.github.io#64]
The Uniswap app fails to load the latest Optimism token list v3.2.2 due to error:

```
List at url https://static.optimism.io/optimism.tokenlist.json could not automatically update because the version bump was only PATCH/MINOR while the update had breaking changes and should have been MAJOR
```

**Comment by elenadimitrova** [comment]
We haven't merged any breaking changes though 🤔 Any more details that can help me pinpoint which update broke this?

**Comment by willhennessy** [comment]
In general a [major version](https://github.com/Uniswap/token-lists#semantic-versioning) is required if (1) a token is removed or (2) a token has its address changed. Are any of those in the diff?

Here is the [interface code](https://github.com/Uniswap/interface/blob/main/src/lib/hooks/useTokenList/validateTokenList.ts) that validates the token list

**Comment by elenadimitrova** [comment]
We haven't removed anything only have added new tokens 🤔 I need to investigate. In the short term if this is urgent I can merge an upgrade to the major version so we fix this at your end?

**Comment by willhennessy** [comment]
Hi Elena, fyi we got a report that users have noticed they aren’t able to wrap/unwrap ETH in the Uniswap app as a result of this

upgrading the major version seems like an easy fix

**Comment by elenadimitrova** [comment]
@willhennessy done. let me know if this persists.

**Comment by willhennessy** [comment]
Thanks Elena! it's fixed
