### ISSUE TITLE
Need more silly meme coins on Optimism / Base.

### ISSUE THREAD

**Issue by faces-of-eth** [ethereum-optimism/ethereum-optimism.github.io#708]
![bananacat-halla](https://github.com/ethereum-optimism/ethereum-optimism.github.io/assets/108703161/0b256ebb-e2ce-4f28-9f5f-ccf91a35ac32)

**Is your feature request related to a problem? Please describe.**
I'm kind of bummed out that Optimism and Base don't have better meme coins.

**Describe the solution you'd like**
Something funny and clever would be nice to interact with on the SuperChain.

**Describe alternatives you've considered**
I've considered spinning up my own memes but I'm not that funny.

**Additional context**
[These videos might help](https://www.youtube.com/results?search_query=banana%20cat)

**Comment by wbnns** [comment]
@faces-of-eth Come hang out in the Base channel on Farcaster, there are a lot of memecoins regularly launching there :) https://warpcast.com/~/channel/base
