### ISSUE TITLE
[Base] Bridging to a different token name and ticker

### ISSUE THREAD

**Issue by trador-rising** [ethereum-optimism/ethereum-optimism.github.io#724]
Hello, I have some questions about bridging on Base using the standard bridge. Is it possible to bridge an ethereum erc-20 to Base, where the new token on Base has a different name and ticker? I see the instructions say "Token name, symbol, and decimals matches on-chain data (auto-reject); If overrides are used (requires manual review)" which suggests this might be possible upon review.

I'm part of a renounced contract project which was taken over by the community 2 years ago after the original dev abandoned it. We have now built a product and are in a good position at multi million mcap and with a dedicated community. However, during our evolution we decided to rebrand away from the original name and ticker. We'd like to rebrand with a new name and ticker on Base but keep it linked to our existing renounced liquidity pool so as not to adversely affect current holders. It would be perfect if this could be achieved via the standard bridge.

Tagging @cfluke-cb as Base reviewer. Furthermore, if this is possible, what steps could we take to be listed on the official Base bridging UI? We have a professional product which we'd like to bring to Base and it would help us a lot to be listed in the UI. I would gladly discuss our project and team further and explore options to get listed in the UI.

Thanks for your kind attention

**Comment by wbnns** [comment]
@trador-rising 

Hi there! Thanks for your patience waiting for a reply! Here's an example of a token that is doing something similar (different symbol and name on L1 compared to Base). https://github.com/ethereum-optimism/ethereum-optimism.github.io/pull/697

In the near future we'll be transitioning away from the official Base bridge in favor of further decentralizing and directing users to other bridges in the community, e.g. https://superbridge.app/base

Community bridges have their own processes for enabling you to include your own token, but being part of the Superchain Token List (this repo) is an important step.

Hope that helps clarify! :)

**Comment by trador-rising** [comment]
Hi @wbnns thanks very much for the reply! It's exciting to know that this will be possible. Are you sure https://github.com/ethereum-optimism/ethereum-optimism.github.io/pull/697 is the correct link? It looks like this token has the same ticker and name on Base and ETH: Open Ecosystem Token (OPN)
