### ISSUE TITLE
List token with name that already exists

### ISSUE THREAD

**Issue by dusan-mrsic** [ethereum-optimism/ethereum-optimism.github.io#845]
Hello everyone,

I wrote this into PR, but that PR is merged so I don't want to lose that.

I want to list token on BASE, but there is already token with same name and symbol. What should be the proper naming for data folder? Token symbol is "CHI".

**Comment by wbnns** [comment]
@dusan-mrsic 

Heya, thanks for your patience on this issue. I think the only workaround here would be to use a different name and then use overrides in the metadata. Here's how:

https://github.com/ethereum-optimism/ethereum-optimism.github.io?tab=readme-ov-file#per-token-overrides

Hope that helps!
